server:
  address:
  port: 8081
spring:
  application:
    name: dubbo-consumer
nacos:
  config:
    server-addr: localhost:8848
dubbo:
  registry:
    address: nacos://${nacos.config.server-addr}
  application:
    name: ${spring.application.name}